In [71]:
import pandas as pd
data=pd.read_csv(r'C:\Users\SNARAHA1\Downloads\mercedes-benz-greener-manufacturing\test.csv\test.csv',
                 usecols= ['X1','X2','X3','X4','X5','X6'])
data

      X1  X2 X3 X4  X5 X6
0      v   n  f  d   t  a
1      b  ai  a  d   b  g
2      v  as  f  d   a  j
3      l   n  f  d   z  l
4      s  as  c  d   y  i
...   ..  .. .. ..  .. ..
4204   h  as  f  d  aa  j
4205  aa  ai  d  d  aa  j
4206   v  as  f  d  aa  d
4207   v  as  a  d  aa  c
4208  aa  ai  c  d  aa  g

[4209 rows x 6 columns]

In [72]:
for col in data.columns:
    print(col, ':',len(data[col].unique()),'labels')

X1 : 27 labels
X2 : 45 labels
X3 : 7 labels
X4 : 4 labels
X5 : 32 labels
X6 : 12 labels

In [73]:
pd.get_dummies(data,drop_first=True)

,X1_aa,X1_ab,X1_b,X1_c,X1_d,X1_e,X1_f,X1_g,X1_h,X1_i,...,X6_c,X6_d,X6_e,X6_f,X6_g,X6_h,X6_i,X6_j,X6_k,X6_l
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4204,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
4205,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
4206,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
4207,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
4208,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0

In [74]:
# working on X2, take top 10 frequent labels and performing and make the other labels to zero
data.X2.value_counts().sort_values(ascending=False).head(20)

as    1658
ae     478
ai     462
m      348
ak     260
r      155
n      113
s      100
f       85
e       84
ay      78
aq      72
a       44
b       38
t       25
k       25
ag      23
ac      20
ao      19
i       15
Name: X2, dtype: int64

In [75]:
top_10=[x for x in data.X2.value_counts().sort_values(ascending=False).head(10).index]
top_10

['as', 'ae', 'ai', 'm', 'ak', 'r', 'n', 's', 'f', 'e']

In [76]:
#make 15 binary variables
import numpy as np
for label in top_10:
    data[label]=np.where(data['X2']==label,1,0)

In [77]:
data

      X1  X2 X3 X4  X5 X6  as  ae  ai  m  ak  r  n  s  f  e
0      v   n  f  d   t  a   0   0   0  0   0  0  1  0  0  0
1      b  ai  a  d   b  g   0   0   1  0   0  0  0  0  0  0
2      v  as  f  d   a  j   1   0   0  0   0  0  0  0  0  0
3      l   n  f  d   z  l   0   0   0  0   0  0  1  0  0  0
4      s  as  c  d   y  i   1   0   0  0   0  0  0  0  0  0
...   ..  .. .. ..  .. ..  ..  ..  .. ..  .. .. .. .. .. ..
4204   h  as  f  d  aa  j   1   0   0  0   0  0  0  0  0  0
4205  aa  ai  d  d  aa  j   0   0   1  0   0  0  0  0  0  0
4206   v  as  f  d  aa  d   1   0   0  0   0  0  0  0  0  0
4207   v  as  a  d  aa  c   1   0   0  0   0  0  0  0  0  0
4208  aa  ai  c  d  aa  g   0   0   1  0   0  0  0  0  0  0

[4209 rows x 16 columns]

In [78]:
data[['X2']+top_10].head(20)

    X2  as  ae  ai  m  ak  r  n  s  f  e
0    n   0   0   0  0   0  0  1  0  0  0
1   ai   0   0   1  0   0  0  0  0  0  0
2   as   1   0   0  0   0  0  0  0  0  0
3    n   0   0   0  0   0  0  1  0  0  0
4   as   1   0   0  0   0  0  0  0  0  0
5   ai   0   0   1  0   0  0  0  0  0  0
6   ae   0   1   0  0   0  0  0  0  0  0
7   ae   0   1   0  0   0  0  0  0  0  0
8    s   0   0   0  0   0  0  0  1  0  0
9   as   1   0   0  0   0  0  0  0  0  0
10   s   0   0   0  0   0  0  0  1  0  0
11   b   0   0   0  0   0  0  0  0  0  0
12   e   0   0   0  0   0  0  0  0  0  1
13  ae   0   1   0  0   0  0  0  0  0  0
14  ak   0   0   0  0   1  0  0  0  0  0
15   e   0   0   0  0   0  0  0  0  0  1
16   s   0   0   0  0   0  0  0  1  0  0
17   e   0   0   0  0   0  0  0  0  0  1
18  ai   0   0   1  0   0  0  0  0  0  0
19  as   1   0   0  0   0  0  0  0  0  0

In [79]:
def one_hot_top_x(df,variable,top_x_labels):
    for label in top_x_labels:
        df[variable+'_'+label]=np.where(data[variable]==label,1,0)
data=pd.read_csv(r'C:\Users\SNARAHA1\Downloads\mercedes-benz-greener-manufacturing\test.csv\test.csv',
                 usecols= ['X1','X2','X3','X4','X5','X6'])
one_hot_top_x(data,'X2',top_10)
data.head(20)

,X1,X2,X3,X4,X5,X6,X2_as,X2_ae,X2_ai,X2_m,X2_ak,X2_r,X2_n,X2_s,X2_f,X2_e
0,v,n,f,d,t,a,0,0,0,0,0,0,1,0,0,0
1,b,ai,a,d,b,g,0,0,1,0,0,0,0,0,0,0
2,v,as,f,d,a,j,1,0,0,0,0,0,0,0,0,0
3,l,n,f,d,z,l,0,0,0,0,0,0,1,0,0,0
4,s,as,c,d,y,i,1,0,0,0,0,0,0,0,0,0
5,aa,ai,e,d,x,g,0,0,1,0,0,0,0,0,0,0
6,b,ae,d,d,x,d,0,1,0,0,0,0,0,0,0,0
7,s,ae,c,d,h,d,0,1,0,0,0,0,0,0,0,0
8,l,s,c,d,h,j,0,0,0,0,0,0,0,1,0,0
9,v,as,f,d,g,f,1,0,0,0,0,0,0,0,0,0
10,l,s,c,d,g,d,0,0,0,0,0,0,0,1,0,0
11,b,b,a,d,g,l,0,0,0,0,0,0,0,0,0,0
12,r,e,f,d,g,h,0,0,0,0,0,0,0,0,0,1
13,v,ae,g,d,g,g,0,1,0,0,0,0,0,0,0,0
14,a,ak,f,d,g,l,0,0,0,0,1,0,0,0,0,0
15,r,e,f,d,g,h,0,0,0,0,0,0,0,0,0,1
16,l,s,c,d,g,d,0,0,0,0,0,0,0,1,0,0
17,r,e,f,d,f,h,0,0,0,0,0,0,0,0,0,1
18,i,ai,a,d,f,l,0,0,1,0,0,0,0,0,0,0
19,r,as,f,d,f,d,1,0,0,0,0,0,0,0,0,0

In [80]:
def one_hot_top_x(df,variable,top_x_labels):
    for label in top_x_labels:
        df[variable+'_'+label]=np.where(data[variable]==label,1,0)
data=pd.read_csv(r'C:\Users\SNARAHA1\Downloads\mercedes-benz-greener-manufacturing\test.csv\test.csv',
                 usecols= ['X1','X2','X3','X4','X5','X6'])
top_10=[x for x in data.X1.value_counts().sort_values(ascending=False).head(10).index]
one_hot_top_x(data,'X1',top_10)
data.head(20)

,X1,X2,X3,X4,X5,X6,X1_aa,X1_s,X1_l,X1_b,X1_v,X1_r,X1_i,X1_a,X1_c,X1_o
0,v,n,f,d,t,a,0,0,0,0,1,0,0,0,0,0
1,b,ai,a,d,b,g,0,0,0,1,0,0,0,0,0,0
2,v,as,f,d,a,j,0,0,0,0,1,0,0,0,0,0
3,l,n,f,d,z,l,0,0,1,0,0,0,0,0,0,0
4,s,as,c,d,y,i,0,1,0,0,0,0,0,0,0,0
5,aa,ai,e,d,x,g,1,0,0,0,0,0,0,0,0,0
6,b,ae,d,d,x,d,0,0,0,1,0,0,0,0,0,0
7,s,ae,c,d,h,d,0,1,0,0,0,0,0,0,0,0
8,l,s,c,d,h,j,0,0,1,0,0,0,0,0,0,0
9,v,as,f,d,g,f,0,0,0,0,1,0,0,0,0,0
10,l,s,c,d,g,d,0,0,1,0,0,0,0,0,0,0
11,b,b,a,d,g,l,0,0,0,1,0,0,0,0,0,0
12,r,e,f,d,g,h,0,0,0,0,0,1,0,0,0,0
13,v,ae,g,d,g,g,0,0,0,0,1,0,0,0,0,0
14,a,ak,f,d,g,l,0,0,0,0,0,0,0,1,0,0
15,r,e,f,d,g,h,0,0,0,0,0,1,0,0,0,0
16,l,s,c,d,g,d,0,0,1,0,0,0,0,0,0,0
17,r,e,f,d,f,h,0,0,0,0,0,1,0,0,0,0
18,i,ai,a,d,f,l,0,0,0,0,0,0,1,0,0,0
19,r,as,f,d,f,d,0,0,0,0,0,1,0,0,0,0